# LLM model
api_key: "sk-07d627a271c349cd8fe8720f2f7c45bb"
model_id: "qwen3-coder-plus"
model_backend: "qwen"
temperature: 1.0

# dataloader
statis_path: "/data/shenqingchao/zibo/GEAK-agent/GEAK-eval/geak_eval/data/TritonBench/data/TritonBench_G_comp_alpac_v1_fixed_with_difficulty.json"
py_folder: "/data/shenqingchao/zibo/GEAK-agent/GEAK-eval/geak_eval/data/TritonBench/data/TritonBench_G_v1"
instruction_path: "/data/shenqingchao/zibo/GEAK-agent/GEAK-eval/geak_eval/data/TritonBench/data/TritonBench_G_comp_alpac_v1_fixed_with_difficulty.json"
corpus_path: "/data/shenqingchao/zibo/GEAK-agent/GEAK-eval/geak_eval/data/TritonBench/data/train_crawl.json"
golden_metrics: "/data/shenqingchao/zibo/GEAK-agent/GEAK-eval/geak_eval/data/TritonBench/performance_metrics/perf_G/golden_metrics"
perf_ref_folder: null
perf_G_path: ""
py_interpreter: "python"


# agent
result_path: null #Resuming from Checkpoints
mem_file: null #Resuming from Checkpoints
start_iter: 0
start_idx: 12
datalen: 1
output_path: "../outputs/20251001_gaagent_offspring8_gpt5.jsonl"
max_iteration: 2
multi_thread: true
ancestor_num: 1   #ancestor number of perf_candidates used to generate descendant
descendant_num: 3 #offspring
gpu_id: 1
descendant_debug: 1 # if descendant_debug of descendant pass execution test, then generate descendant_num of new codes.
target_gpu: "NVIDIA"
profiling: true # use profiling info.